// Copies repository data/config into app/public/data so the app can fetch them.
// Never edit app/public/data by hand: it is generated and git-ignored.
import { cp, mkdir, rm, readdir, stat, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const appDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoDir = path.resolve(appDir, '..');
const outDir = path.join(appDir, 'public', 'data');

const sources = [
  { from: path.join(repoDir, 'data', 'processed'), to: path.join(outDir, 'processed') },
  { from: path.join(repoDir, 'config'), to: path.join(outDir, 'config') },
  { from: path.join(repoDir, 'tests'), to: path.join(outDir, 'tests') },
];

// The parcel-clipped TIN is the authoritative terrain surface for the golden
// slope-band figures, so the app ships it alongside the 2 m DEM.
const singleFiles = [
  {
    from: path.join(repoDir, 'data', 'raw', 'survey', 'mangalapuram_terrain_15_sept.obj'),
    to: path.join(outDir, 'terrain', 'terrain_tin.obj'),
  },
];

async function listFiles(dir, base = dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await listFiles(full, base)));
    else out.push(path.relative(base, full).split(path.sep).join('/'));
  }
  return out;
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

let bytes = 0;
for (const { from, to } of sources) {
  if (!existsSync(from)) throw new Error(`missing source directory: ${from}`);
  await cp(from, to, { recursive: true });
  for (const rel of await listFiles(to)) bytes += (await stat(path.join(to, rel))).size;
}

for (const { from, to } of singleFiles) {
  if (!existsSync(from)) throw new Error(`missing source file: ${from}`);
  await mkdir(path.dirname(to), { recursive: true });
  await cp(from, to);
  bytes += (await stat(to)).size;
}

const manifest = {
  generated_at: new Date().toISOString(),
  note: 'Generated by app/scripts/sync-data.mjs from repo data/processed, config and tests. Do not edit.',
  files: Object.fromEntries(
    await Promise.all(
      [...sources, { to: path.join(outDir, 'terrain') }].map(async ({ to }) => [
        path.relative(outDir, to),
        await listFiles(to),
      ]),
    ),
  ),
};
await writeFile(path.join(outDir, 'manifest.json'), JSON.stringify(manifest, null, 2));
console.log(`sync-data: ${(bytes / 1e6).toFixed(1)} MB -> ${path.relative(repoDir, outDir)}`);
